Ado.netpractice/Models/LogSign.cs
namespace Ado.netpractice.Models
{
    public class LogSign
    {
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
    }
}

Ado.netpractice/Controllers/LogsignController.cs
using Ado.netpractice.Models;
using Ado.netpractice.Services;
using Microsoft.AspNetCore.Mvc;

namespace Ado.netpractice.Controllers
{
    public class LogsignController : Controller
    {
        public readonly IServiceDbConnection _logsign;

        public LogsignController(IServiceDbConnection logsign)
        {
            _logsign = logsign;
        }
        [HttpPost]
        public IActionResult signup(LogSign logdata)
        {
            var signuped = _logsign.Signup(logdata);
            if (signuped)
            {
                return Json(signuped);
            }
            return View(logdata);
        }
    }
}

Ado.netpractice/Views/Logsign/signup.cshtml
@model Ado.netpractice.Models.LogSign


@{
    ViewData["Title"] = "signup";
}

<h1>signup</h1>


<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group mb-2 w-25">
    <input type="text" class="form-control" placeholder="username" id="username" />
    <span asp-validation-for="username" class="text-danger"></span>
</div>
<div class="form-group mb-2  w-25">
    <input type="password" class="form-control" placeholder="password" id="password" />
    <span asp-validation-for="password" class="text-danger"></span>
</div>
<div class="form-group mb-2  w-25">

    <input type="email" class="form-control" placeholder="email" id="email" />
    <span asp-validation-for="email" class="text-danger"></span>
</div>
<div class="form-group">
    <input type="submit" class="btn btn-primary" onclick="signup()" />
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    function signup() {
        var username = $("#username").val();
        var password = $("#password").val();
        var email = $("#email").val();


        $.ajax({
            url: '@Url.Action("signup", "Logsign")',
            type: 'POST',
            dataType: 'json',
            data: {
                username: username,
                password: password,
                email:email
            },
            success: function (response) {
                if (response) {
                    alert("signed up successfuly")
                }
                else {
                    alert("not signedup")
                }
            },
            error: function (xhr, error, status) {
                alert("error")
            }

        })
    }
</script>