Ado.netpractice/Controllers/ProductController.cs
using Ado.netpractice.Models;
using global::Ado.netpractice.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Ado.netpractice.Services.Claims;
using Microsoft.AspNetCore.Authorization;

namespace Ado.netpractice.Controllers
{
    public class ProductController : Controller
    {
        public readonly IServiceDbConnection _productdal;       
        public ProductController(IServiceDbConnection productDal)
        {
            _productdal = productDal;
           
        }
        public IActionResult Index()
        {
            var a = HttpContext.GetClaimsData();
            ViewBag.a = a.username;
            return View();
           
        }
        [Authorize(Policy = "EmployeeOnly")]
        public IActionResult GetProductList()
        {
            return View();
        }
        //inserting data into database
        [HttpPost]
        public IActionResult InsertProductList(ProductRequestModel produtdtls)
        {
            var response = _productdal.Insert_Product(produtdtls);
               
                if (response)
                {     
                    return Json(response);
                }
            // If model validation fails, return to the form with errors
            return View(produtdtls);
        }
        //fetching data from database 
        [HttpGet]
        public IActionResult fetchingdata()
        {
            var ProductDataList = _productdal.Fetching_Data();
            return Json(new {success = true, data = ProductDataList });
        }
        //deleting data using id
        [HttpPost]
        public IActionResult Deleted(int Id)
        {
            var deleted = _productdal.Delete_Product(Id);
            if (deleted)
            {
                return Json(new {success=true});
            }
            else
            {
                return Json(new {success = false });
            }
        }
        //editing data using id
        public IActionResult Edit(ProductRequestModel request)
        {
            var fetched_data = _productdal.Fetching_DataForEdit(request);
            //var stored_data = fetched_data.productList.FirstOrDefault(p => p.ProductId == id);
            return Json(fetched_data);
        }

        [HttpPost]
        public IActionResult Editing(int id, ProductRequestModel prop)
        {
            var result = _productdal.Edit_Product(id,prop);
            if (result)
            {
                return Json(new { success = true });
            }
            else
            {
                return Json(new { success = false });
            }
        }

        [HttpGet]
        public IActionResult Product_Search()
        {
            var ab = HttpContext.GetClaimsData();
            ViewBag.ab = ab.username;
            return View();
        }

        [HttpPost]
        //action to for searching product
        public IActionResult Product_Search(string Itemnames)
        {
            
            var result = _productdal.Product_Search(Itemnames);
            return Json(result);
        }

        [HttpPost]
        //action for ordered_list
        public IActionResult Add_Order_into_List(ProductRequestModel request)
        {

            var result = _productdal.Add_Order_into_List(request);
            return Json(result);
        }
        [HttpPost]
        public IActionResult UpdateQuantity(ProductRequestModel request)
        {
            var response = _productdal.Row_QuantityUpdate(request);

            return Json(response);
        }

        [HttpPost]
        public IActionResult DeleteItemRow(ProductRequestModel request)
        {
            var response = _productdal.DeleteItemRow(request);
            return Json(response);
        }
    }
}

Ado.netpractice/Controllers/User_SetupController.cs
using Ado.netpractice.Models;
using Ado.netpractice.Services.Claims;
using Ado.netpractice.Services.User_Setup;
using Azure;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Ado.netpractice.Controllers
{
    public class User_SetupController : Controller
    {
        public readonly IUser_setup User_Setup;

        public User_SetupController(IUser_setup UserSetup)
        {
            User_Setup = UserSetup;
        }

        [HttpGet]
        public IActionResult User_Signup()
        {
            return View();
        }
        [HttpPost]
        public IActionResult User_Signup(UserSignup Userproperty)
        {
            var response = User_Setup.Users_Signup(Userproperty);
            return Json(new { message = response.ResponseMessage,code = response.ResponseCode });
        }
        [HttpGet]
        public IActionResult User_Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult User_Login(UserResponseModel Userproperty)
        {
            var response = User_Setup.Users_Login(Userproperty);

            var claims = new List<Claim> {
            new Claim("Username",response.UserName),
            new Claim("Password",response.Pwd)   
            };
            var claimIdentity = new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity));

            return Json(new { message = response.ResponseMessage, code = response.ResponseCode });
        }
        public IActionResult AccessDenied()
        {
            var user = HttpContext.GetClaimsData();
            ViewBag.user = user.username;
           
            return View();
        }
    }
}

Ado.netpractice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ado.netpractice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ado.netpractice.styles.css" asp-append-version="true" />
    <link href="~/lib/datatables/css/jquery.datatables.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/jquery.datatables.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/datatables.bootstrap4.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/datatables.bootstrap4.min.css" rel="stylesheet" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom  mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Product" asp-action="Index">Restaurant Management System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Product Setup
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown" mb-5>
                                <li><a class="dropdown-item" asp-controller="Product" asp-action="GetProductList">Create Product</a></li>
                                <li><a class="dropdown-item" asp-controller="Product"  asp-action="Product_Search">Search Product</a></li>
                            </ul>                              
                     
                        </li>
    
                        <li class="nav-item" onclick="logout()" id="logout">
                            <a class="nav-link text-dark" >Logout</a>
                        </li>
                   
                </div>
                </ul>
            </div>
            </div>
        </nav>

    </header>
    <div class="modal" tabindex="-1" role="dialog" id="logoutModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Logout Confirmation</h5>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to logout?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" onclick="confirmLogout()">Logout</button>
                </div>
            </div>
        </div>
    </div>
   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/js/jquery.datatables.js"></script>
    <script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<script>
    function logout(){
        $("#logoutModal").modal('show');
    }
    function confirmLogout() {
        window.location.href = '@Url.Action("User_Login", "User_Setup")';
    }
  
</script>